---
#
# Playbook to install the ELK stack + Beats
#
- hosts: all
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
  - { role: java }
  - { role: elasticsearch }
  - { role: logstash }
  - { role: kibana }
  - { role: metricbeat }
  - { role: restart-services }
  - { role: jenkins}
